# Generated by Django 5.2.5 on 2025-08-12 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"ordering": ["-published"]},
        ),
        migrations.RenameField(
            model_name="news",
            old_name="picture_url",
            new_name="image_url",
        ),
        migrations.RenameField(
            model_name="news",
            old_name="publishing_date",
            new_name="published",
        ),
    ]
